AppBundle\Entity\Card:
    type: entity
    table: card
    repositoryClass: AppBundle\Repository\CardRepository
    gedmo:
        translation:
            locale: locale
    manyToOne:
        pack:
            targetEntity: Pack
            inversedBy: cards
            joinColumn:
                name: pack_id
                referencedColumnName: id
        type:
            targetEntity: Type
            inversedBy: cards
            joinColumn:
                name: type_id
                referencedColumnName: id
        subtype:
            targetEntity: Subtype
            inversedBy: cards
            joinColumn:
                name: subtype_id
                referencedColumnName: id
        faction:
            targetEntity: Faction
            inversedBy: cards
            joinColumn:
                name: faction_id
                referencedColumnName: id
        faction2:
            targetEntity: Faction
            nullable: true
            joinColumn:
                name: faction2_id
                referencedColumnName: id
        card_set:
            targetEntity: Cardset
            inversedBy: cards
            joinColumn:
                name: set_id
                referencedColumnName: id
        linked_to:
            targetEntity: Card
            inversedBy: linked_from
            joinColumn:
                name: linked_id
                referencedColumnName: id
        duplicate_of:
            targetEntity: Card
            inversedBy: duplicates
            joinColumn:
                name: duplicate_id
                referencedColumnName: id
    oneToMany:
        reviews:
            targetEntity: Review
            orderBy: {'dateCreation':'DESC'}
            mappedBy: card
        linked_from:
            targetEntity: Card
            mappedBy: linked_to
        duplicates:
            targetEntity: Card
            orderBy: {'dateCreation':'DESC'}
            mappedBy: duplicate_of
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        position:
            type: smallint
            nullable: false
        setPosition:
            type: smallint
            nullable: true
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
            gedmo:
                - translatable
        realName:
            type: string
            length: 1024
            nullable: false
        subname:
            type: string
            length: 1024
            nullable: true
            gedmo:
                - translatable
        cost:
            type: smallint
            nullable: true
        costPerHero:
            type: boolean
            nullable: true
        text:
            type: text
            nullable: true
            gedmo:
                - translatable
        realText:
            type: text
            nullable: true
        boost:
            type: smallint
            nullable: true
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
        quantity:
            type: smallint
            nullable: false
        resourceEnergy:
            type: smallint
            nullable: true
        resourcePhysical:
            type: smallint
            nullable: true
        resourceMental:
            type: smallint
            nullable: true
        resourceWild:
            type: smallint
            nullable: true
        handSize:
            type: smallint
            nullable: true
        health:
            type: smallint
            nullable: true
        healthPerGroup:
            type: boolean
            nullable: true
        healthPerHero:
            type: boolean
            nullable: true
        thwart:
            type: smallint
            nullable: true
        thwartCost:
            type: smallint
            nullable: true
        scheme:
            type: smallint
            nullable: true
        attack:
            type: smallint
            nullable: true
        attackCost:
            type: smallint
            nullable: true
        defense:
            type: smallint
            nullable: true
        defenseCost:
            type: smallint
            nullable: true
        recover:
            type: smallint
            nullable: true
        recoverCost:
            type: smallint
            nullable: true
        baseThreat:
            type: smallint
            nullable: true
        baseThreatFixed:
            type: boolean
            nullable: true
        baseThreatPerGroup:
            type: boolean
            nullable: true
        escalationThreat:
            type: smallint
            nullable: true
        escalationThreatFixed:
            type: boolean
            nullable: true
        schemeCrisis:
            type: smallint
            nullable: true
        schemeAcceleration:
            type: smallint
            nullable: true
        schemeAmplify:
            type: smallint
            nullable: true
        schemeHazard:
            type: smallint
            nullable: true
        threat:
            type: smallint
            nullable: true
        threatFixed:
            type: boolean
            nullable: true
        threatPerGroup:
            type: boolean
            nullable: true
        deckLimit:
            type: smallint
            nullable: true
            column: deck_limit
        stage:
            type: string
            length: 4
            nullable: true
        traits:
            type: string
            length: 255
            nullable: true
            gedmo:
                - translatable
        realTraits:
            type: string
            length: 255
            nullable: true
        meta:
            type: string
            length: 500
            nullable: true
        deckRequirements:
            type: string
            length: 500
            nullable: true
        deckOptions:
            type: string
            length: 500
            nullable: true
        restrictions:
            type: string
            length: 255
            nullable: true
        flavor:
            type: text
            nullable: true
            gedmo:
                - translatable
        illustrator:
            type: string
            length: 255
            nullable: true
        isUnique:
            type: boolean
            nullable: false
            column: is_unique
        hidden:
            type: boolean
            column: hidden
            options:
                default: false
        permanent:
            type: boolean
            column: permanent
            options:
                default: false
        doubleSided:
            type: boolean
            nullable: true
            column: double_sided
        backText:
            type: text
            nullable: true
            gedmo:
                - translatable
        backFlavor:
            type: text
            nullable: true
            gedmo:
                - translatable
        backName:
            type: string
            length: 1024
            nullable: true
            gedmo:
                - translatable
        octgnId:
            type: string
            nullable: true
            column: octgn_id
        attackStar:
            type: boolean
            nullable: true
            column: attack_star
        thwartStar:
            type: boolean
            nullable: true
            column: thwart_star
        defenseStar:
            type: boolean
            nullable: true
            column: defense_star
        healthStar:
            type: boolean
            nullable: true
            column: health_star
        recoverStar:
            type: boolean
            nullable: true
            column: recover_star
        schemeStar:
            type: boolean
            nullable: true
            column: scheme_star
        boostStar:
            type: boolean
            nullable: true
            column: boost_star
        threatStar:
            type: boolean
            nullable: true
            column: threat_star
        escalationThreatStar:
            type: boolean
            nullable: true
            column: escalation_threat_star
        errata:
            type: text
            nullable: true
    uniqueConstraints:
        card_code_idx:
            columns: [ code ]
